services:
  # Backend - Web Service
  - type: web
    name: laptop-config-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: CLIENT_ORIGIN
        value: https://configforge.onrender.com

  # Frontend - Static Site
  - type: web
    name: ConfigForge
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://laptop-config-backend.onrender.com/api
